source 'https://rubygems.org'
ruby '2.3.3'

gem 'devise'
gem 'puma'
gem 'figaro'
gem 'jbuilder', '~> 2.0'
gem 'pg'
gem 'phony_rails'
gem 'rails', '5.0.2'
gem 'redis'

gem 'autoprefixer-rails'
gem 'bootstrap-sass'
gem 'cloudinary'
gem 'font-awesome-sass'
gem 'geocoder'
gem 'jquery-rails'
gem 'rails-assets-smalot-bootstrap-datetimepicker', source: 'https://rails-assets.org'
gem 'sass-rails'
gem 'simple_form'
gem 'uglifier'


group :development, :test do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'factory_girl_rails', '~> 4.0'
  gem 'faker'
  gem 'listen', '~> 3.0.5'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'rspec-rails'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
